import { Event, EventCategory } from '@/types/events';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Festival de Jazz na Praça',
    description:
      'Uma noite inesquecível com os melhores talentos do jazz local e convidados especiais. Venha se encantar com a música que transforma a cidade.',
    event_date: new Date('2024-07-15T19:00:00Z').toISOString(),
    location: 'Praça Central',
    address: 'Praça Central, 123',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '01310-100',
    category: 'music',
    organizer_id: 'org-1',
    capacity: 500,
    price: 0.0,
    image_url:
      'https://images.unsplash.com/photo-1507874457470-272b3c8d8ee2?auto=format&fit=crop&w=800&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Maratona Solidária da Cidade',
    description:
      'Corra por uma boa causa! Participe da nossa maratona beneficente e ajude a comunidade. Distâncias de 5km, 10km e 21km disponíveis.',
    event_date: new Date('2024-08-20T08:00:00Z').toISOString(),
    location: 'Parque Municipal',
    address: 'Av. Parque Municipal, 1000',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '01234-567',
    category: 'sports',
    organizer_id: 'org-2',
    capacity: 1000,
    price: 25.0,
    image_url:
      'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=800&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Workshop de Culinária Italiana',
    description:
      'Aprenda a fazer massas frescas e molhos autênticos com chefs italianos. Inclui degustação e receitas exclusivas para levar para casa.',
    event_date: new Date('2024-06-10T14:00:00Z').toISOString(),
    location: 'Escola de Culinária Bella',
    address: 'Rua das Flores, 456',
    city: 'Rio de Janeiro',
    state: 'RJ',
    zip_code: '20000-000',
    category: 'food',
    organizer_id: 'org-3',
    capacity: 20,
    price: 150.0,
    image_url:
      'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Exposição de Arte Contemporânea',
    description:
      'Explore as obras de artistas locais e internacionais em uma exposição única. Visitas guiadas disponíveis nos finais de semana.',
    event_date: new Date('2024-07-01T10:00:00Z').toISOString(),
    location: 'Galeria de Arte Moderna',
    address: 'Av. Cultural, 789',
    city: 'Belo Horizonte',
    state: 'MG',
    zip_code: '30112-000',
    category: 'art',
    organizer_id: 'org-4',
    capacity: null,
    price: 30.0,
    image_url:
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=800&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Conferência de Tecnologia e Inovação',
    description:
      'Palestras sobre as últimas tendências em tecnologia, IA, blockchain e startups. Networking e oportunidades de negócio.',
    event_date: new Date('2024-09-15T09:00:00Z').toISOString(),
    location: 'Centro de Convenções',
    address: 'Av. Inovação, 2000',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '04567-890',
    category: 'technology',
    organizer_id: 'org-5',
    capacity: 300,
    price: 200.0,
    image_url:
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Aula de Yoga ao Ar Livre',
    description:
      'Pratique yoga em contato com a natureza. Todos os níveis são bem-vindos. Traga seu tapete e venha relaxar conosco.',
    event_date: new Date('2024-06-08T07:00:00Z').toISOString(),
    location: 'Parque do Ibirapuera',
    address: 'Parque do Ibirapuera',
    city: 'São Paulo',
    state: 'SP',
    zip_code: '04094-000',
    category: 'wellness',
    organizer_id: 'org-6',
    capacity: 50,
    price: 0.0,
    image_url:
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const categoryLabels: Record<EventCategory, string> = {
  music: 'Música',
  sports: 'Esporte',
  food: 'Culinária',
  art: 'Arte',
  education: 'Educação',
  technology: 'Tecnologia',
  health: 'Saúde',
  wellness: 'Bem-estar',
  business: 'Negócios',
  religion: 'Religião',
  community: 'Comunidade',
  entertainment: 'Entretenimento',
  culture: 'Cultura',
  workshop: 'Oficina',
  conference: 'Conferência',
  networking: 'Networking',
  other: 'Outros',
};

